### ISSUE TITLE
No output to Google 2 with O3 Air Unit

### ISSUE THREAD

**Issue by markandkymward** [Qrome/QLiteOSD#10]
No OSD output to Goggles 2 with O3 Air Unit
1. Blue flashing light on unit
2. Soldering verified
3. Power verified
4. Image verified (GPS, IMPERIAL)
5. Goggles Menu Display>Canvas mode (the only option) > either Normal or HD, no joy on either.
6. Verified TX to Airunit RX (white wire on original connector)
7. Good video in low power mode. Raised 1.5m after powerup with no change

**Comment by Qrome** [comment]
That is correct -- if you read the NOTE at the top of the readme.md it says it is NOT compatible with the DJI 03 Air Unit.   It also says this on the product page when you go to purchase it.   Very sorry.  I do not know why DJI chose to change the platform so drastically from the original Air Units and Vista light units.
