### ISSUE TITLE
issues disarming?

### ISSUE THREAD

**Issue by ramiss** [Qrome/QLiteOSD#3]
Hi there!  Thanks for this code.  Its working great for me and the DJI air unit arms and starts recording.  the issue is that the air unit won't respond to a disarm msp command.  Have you seen this issue and do you have any insight?

Thanks!

**Comment by Qrome** [comment]
The QLiteOSD defaults to arm with the change in altitude -- it does not know anything about your disarm from your radio unless you have compiled and turned on the option USE_PWM_ARM  --when using this option you can define a switch to arm and disarm if you run a signal and ground from your RC Rx channel to D5 pin.    Otherwise, you only get the arm action when there is a change in altitude of 1.5 meters.  I hope that helps.

**Comment by ramiss** [comment]
> The QLiteOSD defaults to arm with the change in altitude -- it does not know anything about your disarm from your radio unless you have compiled and turned on the option USE_PWM_ARM --when using this option you can define a switch to arm and disarm if you run a signal and ground from your RC Rx channel to D5 pin. Otherwise, you only get the arm action when there is a change in altitude of 1.5 meters. I hope that helps.

Hey and thanks for the response.  Apologies as I wasn't nearly clear enough.  I'm using the same dji flightmodeflags as you to arm and disarm in my own project and, although the arm flag works, the disarm flag rarely works.  its weird, because it works about 1 in 5 times on my 03 air unit (which should be using the same msp protocols as the original air unit/caddx).  I was curious if you've had similar issues with your code?   I'm curious where you got those flags in the first place as I've had trouble finding them myself.  Without your code I'm not sure I would have found something so concise.

**Comment by Qrome** [comment]
It works in my code.   I have not looked at that code for a while but I use it and is working.

**Comment by PPPRY** [comment]
I can not get the latest code to upload using a ESP32-S3-Box has anyone run into any issues flashing? Compilation error: 'LED_BUILTIN' was not declared in this scope @ramiss

**Comment by ramiss** [comment]
> I can not get the latest code to upload using a ESP32-S3-Box has anyone run into any issues flashing? Compilation error: 'LED_BUILTIN' was not declared in this scope @ramiss

So first of all, I'm not the owner of this code, this thread was for my issue.  Second, you need to post your own issue as your problem has nothing to do with not disarming.

**Comment by PPPRY** [comment]
> > I can not get the latest code to upload using a ESP32-S3-Box has anyone run into any issues flashing? Compilation error: 'LED_BUILTIN' was not declared in this scope @ramiss
> 
> So first of all, I'm not the owner of this code, this thread was for my issue. Second, you need to post your own issue as your problem has nothing to do with not disarming.

Gotcha thanks for reaching out first time posting!

**Comment by PPPRY** [comment]
> I can not get the latest code to upload using a ESP32-S3-Box has anyone run into any issues flashing? Compilation error: 'LED_BUILTIN' was not declared in this scope

Sorry disregard this..
