### ISSUE TITLE
Support the battery to 6s 

### ISSUE THREAD

**Issue by astray1988** [Qrome/QLiteOSD#4]
I would expect to have 6s battery(4.2v for Lipo, 4.35 for LiHV) supported in the future release.

**Comment by Qrome** [comment]
It is a hardware limitation.   The you can run what ever your voltage stepdown can handle.   Also, you need to also stay under the voltage limit of your DJI video transmitter unless you use a voltage step down for that as well.   There will be no code changes for this request.
